#!/bin/bash

# source this file to set enstore environment

# Function definitions

# Add [default: prepend] arg1 to PATH only once thus this file can be sourced multiple times.
# Use 2nd argument "after" to append arg1 to $PATH.
# Do not mess with pathmunge (unset) in /etc/profile
_pathmunge() {
    if ! [[ $PATH =~ (^|:)$1($|:) ]] ; then
        if [[ ${2:-} == after ]] ; then
            PATH=$PATH:$1;
        else
            PATH=$1:$PATH;
        fi
    fi
}

# where is enstore code?
rpm -q enstore > /dev/null
if [ $? -ne 0 ]; then
	echo "Enstore rpm is not installed"
    # if executed - exit, if sourced - return :
    [[ x"${BASH_SOURCE[0]}" == x"$0" ]] && exit 1 || return 1
fi
export ENSTORE_DIR=/$(rpm -q --queryformat "%{instprefixes}\n" enstore)

# Directories for enstore submodules and tools
export PYTHON_DIR=$ENSTORE_DIR/Python
export FTT_DIR=$ENSTORE_DIR/FTT

# These use absolute paths:
export ENSTORE_OUT=/var/log/enstore
export FARMLETS_DIR=/usr/local/etc/farmlets

# build PATH:
_pathmunge $ENSTORE_DIR/tools
_pathmunge $ENSTORE_DIR/bin
_pathmunge $ENSTORE_DIR/sbin
_pathmunge $PYTHON_DIR/bin

unset _pathmunge

# definitions for python installed in enstore subtree
export PYTHONINC=$(ls -d $PYTHON_DIR/include/python*)
export PYTHONLIB=$(ls -d $PYTHON_DIR/lib/python*)
export PYTHONPATH=$ENSTORE_DIR:$ENSTORE_DIR/src:$ENSTORE_DIR/modules:$ENSTORE_DIR/HTMLgen:$ENSTORE_DIR/PyGreSQL
export PYTHONUNBUFFERED="x";

# These urls are used to configure git to point to central enstore repositories at FNAL.
#   ENSTORE_GIT - for code
#   ENSTORE_CONF_GIT - site specific configuration
# Once repository configured, you operate through remote alias and do not need this anymore
# Example:
#   git clone -o enstore ${ENSTORE_GIT}
#export ENSTORE_GIT=ssh://p-enstore@cdgit.fnal.gov/cvs/projects/enstore
#export ENSTORE_CONF_GIT=ssh://p-enstore-config@cdgit.fnal.gov/cvs/projects/enstore-config

# if using ssh for enstore node communications for distribution, upgrade, and maintenance
# uncomment the following lines
#export ENSSH=/usr/bin/ssh
#export ENSCP=/usr/bin/scp

#-----------------------------------------------------------------------------------------
# Enstore site specific configuration files
# These files come from enstore-config git repository
# ENSTORE_HOME=/home/enstore is referenced as default location at /usr/local/etc/setups.sh
export ENSTORE_HOME=${ENSTORE_HOME:-/home/enstore}
export HOME=${HOME:-${ENSTORE_HOME}} # set if does not exist such as for cgi

export ENSTORE_CONFIG_DIR=${ENSTORE_HOME}/site_specific

# Customize settings between enstore systems.
# The files are looked at ${ENSTORE_CONFIG_DIR}/config
# Try to source setup-enstore.local if it exist
# The customization script shall look like:
# enstore-setup.local :
#   ENSTORE_CONFIG_HOST=hostname.domain or host IP
#   ENSTORE_CONFIG_FILE=${ENSTORE_CONFIG_DIR}/enstore-system.conf
#   ENSTORE_MAIL=<enstore admin email address>
#
# There are preconfigured files for existing systems like
#   enstore-setup.stken :
# During enstore installation/configuration this or similar script shall be copied to enstore-setup.local
#
# If someone need to customize one node only, create file like setup-enstore.dmsen02
#   enstore-setup.local is ignored in this case.
# See file setup-enstore.README for further details.


# Defaults:
ENSTORE_CONFIG_PORT=7500
#ENSTORE_MAIL=enstore-auto@fnal.gov

# Customize for local subsystem
CUSTOM_CONFIG=${ENSTORE_CONFIG_DIR}/config/setup-enstore.local
if [[ -r ${CUSTOM_CONFIG} ]]; then
    source ${CUSTOM_CONFIG}
else
    echo "${CUSTOM_CONFIG} does not exist. Create it using ${ENSTORE_DIR}/site_specific/config/setup-enstore.local.template"
    exit 1
fi
export ENSTORE_CONFIG_HOST ENSTORE_CONFIG_PORT ENSTORE_CONFIG_FILE ENSTORE_MAIL
[[ ${ENSTORE_SFA_POLICY:-x} == "x" ]] || export ENSTORE_SFA_POLICY

# if executed - exit, if sourced - return :
[[ x"${BASH_SOURCE[0]}" == x"$0" ]] && exit 0 || return 0
