#!/bin/bash

if [ "`whoami`" != 'root' ]
then
    echo You need to run this script as user "root"
    exit 1
fi

PATH=/usr/sbin:$PATH

chmod +x web_server
chmod +x make_enstore_system
./web_server --install

if [ $? != 0 ];
then
	exit 1 
fi
./make_enstore_system

rc=$?

if [ ${rc} == 2 ]; then
    systemctl is-enabled httpd.service
    if [ $? -ne 0 ]; then
	systemctl disable httpd.service
    fi
    exit 0
elif  [ ${rc} == 0 ]; then
    systemctl enable httpd.service
    systemctl start httpd.service
    exit 0
else 
    exit 1
fi

exit 0 
