#!/bin/sh

lastNhours=`date --date "48 hours ago" +"%Y-%m-%d:%H"`
now=`date +"%Y-%m-%d:%H:%M:%S"`
${ENSTORE_DIR}/sbin/plotter --sg --start_time $lastNhours
#cp $od/enplot_sg.ps $log_d/enplot_sg-$now.ps
